### ISSUE TITLE
User can view a list of favorite Twitch channels.

### ISSUE THREAD

**Issue by xmichelle** [xmichelle/twitch-time#2]
# Motivation
User should be able to view a list of favorite streamers with details of each streamer.
# Implementation
- [x] Create a wireframe.
- [x] Be able to add a favorite.
- [x] Be able to toggle view between favorites and search. 
- [x] On the favorites, on active be able to load the data in real-time. 
- [x] Be able to fetch all the information requested. 
- [x] Understand react-router. 
- [x] Allow views to be flipped back and forth with a tab view. 

# Wireframe
![image](https://user-images.githubusercontent.com/29046211/29086251-d2fc21d8-7c26-11e7-8698-feb4dd1108ae.png)

**Comment by kenk2** [comment]
I will be working on this one!
Note: I need to create a react-router for this too. Investigate the use of react-router.
